<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PoojaGadekar" name="com.magicbricks.regressiontest.RegistrationScenario" tests="2" failures="1" timestamp="21 Apr 2016 21:05:26 GMT" time="48.015" errors="0">
  <testcase name="RegistrationScenarioTestTC_01" time="8.773" classname="com.magicbricks.regressiontest.RegistrationScenario"/>
  <testcase name="RegistrationScenarioTestTC_02" time="39.242" classname="com.magicbricks.regressiontest.RegistrationScenario">
    <failure type="java.lang.AssertionError" message="expected [Didn&#039;t Receive the SMS?] but found [Enter OTP]">
      <![CDATA[java.lang.AssertionError: expected [Didn't Receive the SMS?] but found [Enter OTP]
	at org.testng.Assert.fail(Assert.java:94)
	at com.magicbricks.regressiontest.RegistrationScenario.RegistrationScenarioTestTC_02(RegistrationScenario.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- RegistrationScenarioTestTC_02 -->
</testsuite> <!-- com.magicbricks.regressiontest.RegistrationScenario -->
